### ISSUE TITLE
multiple document rules

### ISSUE THREAD

**Issue by silverwind** [350d/stylish#9]
It looks like multiple document (which are mostly in the form of `@-moz-document`) rules are unsupported, while a number of userstyles rely on this functionality. Through https://github.com/StylishThemes/StackOverflow-Dark/issues/21 I discovered that a style like
```css
@-moz-document domain("site1.com") {
 a { color: red }
}
@-moz-document domain("site2.com") {
 a { color: green }
}
```
results in the green `a` style being applied to `site1.com` as well. I assume the second rule wins because it is last.
